# Generated by Django 4.2.30 on 2026-06-28 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_lineaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_centered', models.IntegerField(default=0)),
                ('max_bookings_per_friend', models.IntegerField(blank=True, null=True)),
                ('requires_approval', models.IntegerField(default=0)),
                ('cancel_deadline_hours_before', models.IntegerField(blank=True, null=True)),
                ('reminder_day_before_enabled', models.IntegerField(default=0)),
                ('reminder_hours_before', models.IntegerField(blank=True, null=True)),
                ('is_published', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('target_type', models.CharField(choices=[('single', 'single'), ('multi-account-dedup', 'multi-account-dedup')], default='single', max_length=32)),
                ('account_ids', models.JSONField(blank=True, null=True)),
                ('dedup_priority', models.JSONField(blank=True, null=True)),
                ('line_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='events.event')),
            ],
            options={
                'db_table': 'event_slots',
                'ordering': ['sort_order', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('cancelled', 'cancelled'), ('attended', 'attended'), ('no_show', 'no_show')], default='pending', max_length=12)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=32, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='crm.friend')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.eventslot')),
            ],
            options={
                'db_table': 'event_bookings',
                'ordering': ['-requested_at'],
            },
        ),
    ]
