# Generated by Django 4.2.30 on 2026-06-28 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_lineaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('message_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rich_menu_message_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RichMenuGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chat_bar_text', models.CharField(default='メニュー', max_length=14)),
                ('size', models.CharField(choices=[('large', 'large'), ('compact', 'compact')], default='large', max_length=10)),
                ('default_page_id', models.UUIDField(blank=True, null=True)),
                ('is_default_for_all', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=10)),
                ('publishing_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_r2_key', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rich_menu_groups', to='crm.lineaccount')),
            ],
            options={
                'db_table': 'rich_menu_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RichMenuPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('alias_id', models.CharField(blank=True, default='', max_length=255)),
                ('line_richmenu_id', models.CharField(blank=True, max_length=255, null=True)),
                ('image_r2_key', models.CharField(blank=True, max_length=512, null=True)),
                ('image_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='richmenu.richmenugroup')),
            ],
            options={
                'db_table': 'rich_menu_pages',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='RichMenuArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bounds_x', models.IntegerField(default=0)),
                ('bounds_y', models.IntegerField(default=0)),
                ('bounds_width', models.IntegerField(default=0)),
                ('bounds_height', models.IntegerField(default=0)),
                ('action_type', models.CharField(choices=[('uri', 'uri'), ('message', 'message'), ('postback', 'postback'), ('richmenuswitch', 'richmenuswitch')], default='uri', max_length=20)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='richmenu.richmenupage')),
            ],
            options={
                'db_table': 'rich_menu_areas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_recipients', to='crm.lineaccount')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_recipient_of', to='crm.friend')),
            ],
            options={
                'db_table': 'rich_menu_test_recipients',
                'ordering': ['created_at'],
                'unique_together': {('account', 'friend')},
            },
        ),
    ]
