# Generated by Django 4.2.30 on 2026-06-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
