# Generated by Django 4.2.30 on 2026-06-28 03:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_user_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('picture_url', models.TextField(blank=True, null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('is_following', models.BooleanField(default=True)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ref_code', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'friends',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.friend')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.tag')),
            ],
            options={
                'db_table': 'friend_tags',
                'unique_together': {('friend', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='friend',
            name='tags',
            field=models.ManyToManyField(related_name='friends', through='crm.FriendTag', to='crm.tag'),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('flex', 'flex')], max_length=10)),
                ('message_content', models.TextField()),
                ('target_type', models.CharField(choices=[('all', 'all'), ('tag', 'tag'), ('segment', 'segment'), ('multi-account-dedup', 'multi-account-dedup')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('sending', 'sending'), ('sent', 'sent')], default='draft', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='crm.tag')),
            ],
            options={
                'db_table': 'broadcasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
