# Generated by Django 4.2.30 on 2026-06-28 03:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('friend_add', 'friend_add'), ('tag_added', 'tag_added'), ('manual', 'manual')], max_length=20)),
                ('line_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_mode', models.CharField(choices=[('relative', 'relative'), ('elapsed', 'elapsed'), ('absolute_time', 'absolute_time')], default='relative', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_scenarios', to='crm.tag')),
            ],
            options={
                'db_table': 'scenarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='general', max_length=50)),
                ('message_type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('flex', 'flex')], default='text', max_length=10)),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('incoming', 'incoming'), ('outgoing', 'outgoing')], max_length=10)),
                ('message_type', models.CharField(default='text', max_length=10)),
                ('content', models.TextField()),
                ('delivery_type', models.CharField(blank=True, max_length=10, null=True)),
                ('line_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.friend')),
            ],
            options={
                'db_table': 'messages_log',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'active'), ('paused', 'paused'), ('completed', 'completed'), ('delivering', 'delivering')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('next_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_enrollments', to='crm.friend')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='crm.scenario')),
            ],
            options={
                'db_table': 'friend_scenarios',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('unread', 'unread'), ('in_progress', 'in_progress'), ('resolved', 'resolved')], default='unread', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='crm.friend')),
            ],
            options={
                'db_table': 'chats',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'exact'), ('contains', 'contains')], default='contains', max_length=10)),
                ('response_type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('flex', 'flex')], default='text', max_length=10)),
                ('response_content', models.TextField()),
                ('line_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_replies', to='crm.template')),
            ],
            options={
                'db_table': 'auto_replies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField()),
                ('delay_minutes', models.IntegerField(default=0)),
                ('message_type', models.CharField(choices=[('text', 'text'), ('image', 'image'), ('flex', 'flex')], default='text', max_length=10)),
                ('message_content', models.TextField()),
                ('offset_days', models.IntegerField(blank=True, null=True)),
                ('offset_minutes', models.IntegerField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('on_reach_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reach_steps', to='crm.tag')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.scenario')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_steps', to='crm.template')),
            ],
            options={
                'db_table': 'scenario_steps',
                'ordering': ['step_order'],
                'unique_together': {('scenario', 'step_order')},
            },
        ),
    ]
