# Generated by Django 4.2.30 on 2026-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_scenario_template_message_friendscenario_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('line_channel_access_token', models.TextField(blank=True, default='')),
                ('line_channel_secret', models.CharField(blank=True, default='', max_length=255)),
                ('relay_shared_secret', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'line_settings',
            },
        ),
    ]
