# Generated by Django 4.2.30 on 2026-06-28 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_linesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('channel_access_token', models.TextField(blank=True, default='')),
                ('channel_secret', models.CharField(blank=True, default='', max_length=255)),
                ('login_channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('login_channel_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('liff_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'line_accounts',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
