# Generated by Django 4.2.30 on 2026-06-28 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_lineaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('category_label', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('buffer_after_minutes', models.IntegerField(default=0)),
                ('base_price', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking_menus',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image_url', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_designation_optional', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking_staff',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'requested'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('no_show', 'no_show')], default='requested', max_length=12)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('price_at_booking', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='crm.friend')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='booking.bookingmenu')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='booking.bookingstaff')),
            ],
            options={
                'db_table': 'booking_requests',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_offered', models.IntegerField(default=1)),
                ('override_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('override_price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_menus', to='booking.bookingmenu')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_menus', to='booking.bookingstaff')),
            ],
            options={
                'db_table': 'booking_staff_menus',
                'unique_together': {('staff', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='booking.bookingstaff')),
            ],
            options={
                'db_table': 'booking_shifts',
                'ordering': ['work_date', 'start_time'],
                'unique_together': {('staff', 'work_date', 'start_time')},
            },
        ),
    ]
