# Generated by Django 4.2.30 on 2026-06-28 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_lineaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_account', models.ForeignKey(blank=True, db_column='active_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_pools', to='crm.lineaccount')),
            ],
            options={
                'db_table': 'traffic_pools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_account', models.ForeignKey(db_column='line_account_id', on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='crm.lineaccount')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='pools.trafficpool')),
            ],
            options={
                'db_table': 'pool_accounts',
                'ordering': ['created_at'],
                'unique_together': {('pool', 'line_account')},
            },
        ),
    ]
